name: Go CI

on:
    push:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.24.1"
            - name: Lint
              uses: golangci/golangci-lint-action@v4
              with:
                  args: run --timeout 5m ./task

    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.24.1"
            - name: Run tests
              run: go test -race -timeout=5s -cpu=1,2,4 -count=10 ./task
