name: Go CI

on:
  push:

jobs:
  test:
    if: always()
    runs-on: ubuntu-latest
    env:
      CI: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.1"
      - name: Run tests
        run: go test -race -timeout=5m -cpu=1,2,4 -count=10 ./...
